    // donderdag van 8 to 24 uur 

    var do8 = ""
    var do9 = ""
    var do10 = ""
    var do11 = ""
    var do12 = ""
    var do13 = "donderdag dingen?"
    var do14 = ""
    var do15 = ""
    var do16 = ""
    var do17 = ""
    var do18 = ""
    var do19 = ""
    var do20 = ""
    var do21 = ""
    var do22 = ""
    var do23 = ""
    var do24 = ""