    // vrijdag van 8 to 24 uur 

    var vr8 = ""
    var vr9 = ""
    var vr10 = ""
    var vr11 = ""
    var vr12 = ""
    var vr13 = "vrijdag dingen?"
    var vr14 = ""
    var vr15 = ""
    var vr16 = ""
    var vr17 = ""
    var vr18 = ""
    var vr19 = ""
    var vr20 = "Cisco lezen ;)"
    var vr21 = "It lezen ;)"
    var vr22 = ""
    var vr23 = ""
    var vr24 = ""