    // zaterdag van 8 to 24 uur 

    var za8 = ""
    var za9 = ""
    var za10 = ""
    var za11 = ""
    var za12 = ""
    var za13 = ""
    var za14 = "wakker worden."
    var za15 = "ontbijt"
    var za16 = "games"
    var za17 = "games"
    var za18 = "games"
    var za19 = "avondeten"
    var za20 = "games"
    var za21 = "games"
    var za22 = "games"
    var za23 = "games"
    var za24 = "games (rond 2 uur slapen.)"