    // zondag van 8 to 24 uur 

    var zo8 = ""
    var zo9 = ""
    var zo10 = ""
    var zo11 = ""
    var zo12 = ""
    var zo13 = ""
    var zo14 = "wakker worden."
    var zo15 = "ontbijt"
    var zo16 = "games"
    var zo17 = "games"
    var zo18 = "games"
    var zo19 = "avondeten"
    var zo20 = "games"
    var zo21 = "games"
    var zo22 = "games"
    var zo23 = "games"
    var zo24 = "games (rond 2 uur slapen.)"